# Database Connection Settings with Local Fallbacks for Testing
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/pulse_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:NOTHINGPHONE}

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=TRACE